# Generated by Django 6.0.6 on 2026-07-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0004_anagrafica_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagrafica',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('fornitore', 'Fornitore'), ('centro_assistenza', 'Centro Assistenza')], default='cliente', max_length=20, verbose_name='Tipo'),
        ),
    ]
