# Generated by Django 6.0.6 on 2026-07-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0005_anagrafica_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anagrafica',
            options={'ordering': ['cognome', 'nome', 'ragione_sociale'], 'verbose_name': 'Anagrafica', 'verbose_name_plural': 'Anagrafiche'},
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='cognome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cognome'),
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
