# Generated by Django 6.0.6 on 2026-07-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0007_anagrafica_cliente_prezioso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='documento_tipo',
            field=models.CharField(blank=True, choices=[('carta_identita', 'Carta di Identità'), ('patente', 'Patente'), ('passaporto', 'Passaporto')], max_length=50, verbose_name='Tipo documento'),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='tipo',
            field=models.CharField(choices=[('residenza', 'Residenza'), ('sede_legale', 'Sede legale'), ('sede_operativa', 'Sede operativa'), ('fatturazione', 'Fatturazione'), ('spedizione', 'Spedizione'), ('altro', 'Altro')], default='sede_operativa', max_length=30, verbose_name='Tipo'),
        ),
    ]
