# Generated by Django 6.0.6 on 2026-07-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0008_anagrafica_documento_tipo_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrafica',
            name='documento_tipo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo documento'),
        ),
    ]
