# Generated by Django 6.0.6 on 2026-07-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0010_anagrafica_codice_gestionale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anagrafica',
            options={'ordering': ['cognome', 'nome', 'ragione_sociale'], 'permissions': [('import_clienti_csv', 'Può importare clienti da CSV')], 'verbose_name': 'Anagrafica', 'verbose_name_plural': 'Anagrafiche'},
        ),
    ]
