# Generated by Django 6.0.6 on 2026-07-09 01:27

import apps.core.models.azienda
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('ragione_sociale', models.CharField(max_length=200, verbose_name='Ragione sociale')),
                ('partita_iva', models.CharField(blank=True, max_length=20, verbose_name='Partita IVA')),
                ('codice_fiscale', models.CharField(blank=True, max_length=20, verbose_name='Codice fiscale')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('pec', models.EmailField(blank=True, max_length=254, verbose_name='PEC')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Telefono')),
                ('sito_web', models.URLField(blank=True, verbose_name='Sito web')),
                ('indirizzo', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('civico', models.CharField(blank=True, max_length=20, verbose_name='Civico')),
                ('cap', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('comune', models.CharField(blank=True, max_length=100, verbose_name='Comune')),
                ('provincia', models.CharField(blank=True, max_length=2, verbose_name='Provincia')),
                ('logo', models.FileField(blank=True, upload_to=apps.core.models.azienda.azienda_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'svg'])], verbose_name='Logo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Azienda',
                'verbose_name_plural': 'Aziende',
                'ordering': ['ragione_sociale'],
            },
        ),
    ]
