# Generated by Django 6.0.6 on 2026-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_configurazione_programma_mailto_corpo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurazioneprogramma',
            options={'permissions': [('access_parametri_programma', 'Può gestire Parametri programma')], 'verbose_name': 'Configurazione programma', 'verbose_name_plural': 'Configurazioni programma'},
        ),
        migrations.AlterField(
            model_name='configurazioneprogramma',
            name='mailto_corpo',
            field=models.TextField(blank=True, help_text='Corpo precompilato nel client di posta dai filtri Non ritirate / Ritardo lavorazione. Segnaposto: {codice}, {cliente}, {nome}, {cognome}, {cellulare}, {telefono}.', verbose_name='Testo della mail'),
        ),
        migrations.AlterField(
            model_name='configurazioneprogramma',
            name='mailto_oggetto',
            field=models.CharField(blank=True, default='Riparazione {codice} - {cliente}', help_text='Oggetto precompilato quando si apre il client di posta dai filtri Non ritirate / Ritardo lavorazione. Segnaposto: {codice}, {cliente}, {nome}, {cognome}.', max_length=200, verbose_name='Oggetto della mail'),
        ),
    ]
