# Generated by Django 6.0.6 on 2026-07-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_configurazione_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurazioneprogramma',
            name='layout_stile',
            field=models.CharField(choices=[('standard', 'Grafica standard'), ('compatta', 'Grafica compatta')], default='standard', help_text='Standard: layout arioso. Compatta: stesse informazioni con meno spazi su Riparazioni e Anagrafiche.', max_length=20, verbose_name='Stile grafica maschere'),
        ),
    ]
