from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_configurazione_pc_busta_stampa_senza_anteprima"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurazionepc",
            name="pratica_tasto_salva",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Disabilitato"),
                    ("Ctrl+S", "Ctrl+S"),
                    ("Ctrl+P", "Ctrl+P"),
                    ("Ctrl+B", "Ctrl+B"),
                    ("Ctrl+Enter", "Ctrl+Enter"),
                    ("Ctrl+Shift+S", "Ctrl+Shift+S"),
                    ("Ctrl+Shift+P", "Ctrl+Shift+P"),
                    ("Ctrl+Shift+B", "Ctrl+Shift+B"),
                    ("Esc", "Esc"),
                    ("F5", "F5"),
                    ("F6", "F6"),
                    ("F7", "F7"),
                    ("F8", "F8"),
                    ("F9", "F9"),
                    ("F10", "F10"),
                ],
                default="Ctrl+S",
                help_text="Scorciatoia per Salva nella maschera riparazione.",
                max_length=20,
                verbose_name="Tasto Salva riparazione",
            ),
        ),
        migrations.AddField(
            model_name="configurazionepc",
            name="pratica_tasto_annulla",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Disabilitato"),
                    ("Ctrl+S", "Ctrl+S"),
                    ("Ctrl+P", "Ctrl+P"),
                    ("Ctrl+B", "Ctrl+B"),
                    ("Ctrl+Enter", "Ctrl+Enter"),
                    ("Ctrl+Shift+S", "Ctrl+Shift+S"),
                    ("Ctrl+Shift+P", "Ctrl+Shift+P"),
                    ("Ctrl+Shift+B", "Ctrl+Shift+B"),
                    ("Esc", "Esc"),
                    ("F5", "F5"),
                    ("F6", "F6"),
                    ("F7", "F7"),
                    ("F8", "F8"),
                    ("F9", "F9"),
                    ("F10", "F10"),
                ],
                default="Esc",
                help_text="Scorciatoia per Annulla nella maschera riparazione.",
                max_length=20,
                verbose_name="Tasto Annulla riparazione",
            ),
        ),
        migrations.AddField(
            model_name="configurazionepc",
            name="pratica_tasto_stampa_busta",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Disabilitato"),
                    ("Ctrl+S", "Ctrl+S"),
                    ("Ctrl+P", "Ctrl+P"),
                    ("Ctrl+B", "Ctrl+B"),
                    ("Ctrl+Enter", "Ctrl+Enter"),
                    ("Ctrl+Shift+S", "Ctrl+Shift+S"),
                    ("Ctrl+Shift+P", "Ctrl+Shift+P"),
                    ("Ctrl+Shift+B", "Ctrl+Shift+B"),
                    ("Esc", "Esc"),
                    ("F5", "F5"),
                    ("F6", "F6"),
                    ("F7", "F7"),
                    ("F8", "F8"),
                    ("F9", "F9"),
                    ("F10", "F10"),
                ],
                default="Ctrl+P",
                help_text="Scorciatoia per Stampa busta nella maschera riparazione.",
                max_length=20,
                verbose_name="Tasto Stampa busta",
            ),
        ),
        migrations.AddField(
            model_name="configurazionepc",
            name="pratica_tasto_stampa_privacy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Disabilitato"),
                    ("Ctrl+S", "Ctrl+S"),
                    ("Ctrl+P", "Ctrl+P"),
                    ("Ctrl+B", "Ctrl+B"),
                    ("Ctrl+Enter", "Ctrl+Enter"),
                    ("Ctrl+Shift+S", "Ctrl+Shift+S"),
                    ("Ctrl+Shift+P", "Ctrl+Shift+P"),
                    ("Ctrl+Shift+B", "Ctrl+Shift+B"),
                    ("Esc", "Esc"),
                    ("F5", "F5"),
                    ("F6", "F6"),
                    ("F7", "F7"),
                    ("F8", "F8"),
                    ("F9", "F9"),
                    ("F10", "F10"),
                ],
                default="Ctrl+Shift+P",
                help_text="Scorciatoia per Stampa Privacy nella maschera riparazione.",
                max_length=20,
                verbose_name="Tasto Stampa Privacy",
            ),
        ),
    ]
