# Generated by Django 6.0.6 on 2026-09-06 02:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_configurazione_pc_pratica_stato_radio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurazionemssql',
            name='iva_aliquota_cassa',
            field=models.DecimalField(decimal_places=2, default=Decimal('22.00'), help_text='Valore PRZ_IVA_ALIQUOTA (es. 22.00).', max_digits=5, verbose_name='Aliquota IVA'),
        ),
        migrations.AlterField(
            model_name='configurazionemssql',
            name='iva_id_cassa',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Valore PRZ_IVA_ID scritto su TB_PREZZICASSE (default 10).', null=True, verbose_name='ID_IVA_CASSA'),
        ),
        migrations.AlterField(
            model_name='stampante',
            name='gap_busta_inferiore',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sposta solo la parte B (mm, due decimali). Positivo = più in basso.', max_digits=8, verbose_name='Gap busta inferiore'),
        ),
        migrations.AlterField(
            model_name='stampante',
            name='gap_busta_superiore',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sposta solo la parte A (mm, due decimali). Positivo = più in basso.', max_digits=8, verbose_name='Gap busta superiore'),
        ),
        migrations.AlterField(
            model_name='stampante',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da'),
        ),
    ]
