# Generated by Django 6.0.6 on 2026-09-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_configurazione_pc_pratica_tasti_riparatore_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazioneprogramma',
            name='ddt_aspetto_beni',
            field=models.CharField(blank=True, default='SACCHETTO', max_length=80, verbose_name='Aspetto beni DDT predefinito'),
        ),
        migrations.AddField(
            model_name='configurazioneprogramma',
            name='ddt_causale',
            field=models.CharField(blank=True, default='C/RIPARAZIONE', max_length=80, verbose_name='Causale DDT predefinita'),
        ),
        migrations.AddField(
            model_name='configurazioneprogramma',
            name='ddt_sezionale',
            field=models.CharField(blank=True, default='R', help_text='Suffisso numerazione DDT (es. R → 100/R).', max_length=10, verbose_name='Sezionale DDT'),
        ),
        migrations.AddField(
            model_name='configurazioneprogramma',
            name='ddt_trasporto_a_cura',
            field=models.CharField(blank=True, default='Vettore', max_length=80, verbose_name='Trasporto a cura DDT predefinito'),
        ),
        migrations.AddField(
            model_name='configurazioneprogramma',
            name='ddt_vettore',
            field=models.CharField(blank=True, default='GLS', max_length=120, verbose_name='Vettore DDT predefinito'),
        ),
        migrations.AlterField(
            model_name='configurazionepc',
            name='pratica_tasto_annulla',
            field=models.CharField(blank=True, choices=[('', 'Disabilitato'), ('Ctrl+S', 'Ctrl+S'), ('Ctrl+P', 'Ctrl+P'), ('Ctrl+B', 'Ctrl+B'), ('Ctrl+Enter', 'Ctrl+Enter'), ('Ctrl+Shift+S', 'Ctrl+Shift+S'), ('Ctrl+Shift+P', 'Ctrl+Shift+P'), ('Ctrl+Shift+B', 'Ctrl+Shift+B'), ('Esc', 'Esc'), ('F5', 'F5'), ('F6', 'F6'), ('F7', 'F7'), ('F8', 'F8'), ('F9', 'F9'), ('F10', 'F10')], default='Esc', help_text='Scorciatoia per Annulla nella maschera riparazione (stessa in anagrafica cliente).', max_length=20, verbose_name='Tasto Annulla riparazione'),
        ),
        migrations.AlterField(
            model_name='configurazionepc',
            name='pratica_tasto_salva',
            field=models.CharField(blank=True, choices=[('', 'Disabilitato'), ('Ctrl+S', 'Ctrl+S'), ('Ctrl+P', 'Ctrl+P'), ('Ctrl+B', 'Ctrl+B'), ('Ctrl+Enter', 'Ctrl+Enter'), ('Ctrl+Shift+S', 'Ctrl+Shift+S'), ('Ctrl+Shift+P', 'Ctrl+Shift+P'), ('Ctrl+Shift+B', 'Ctrl+Shift+B'), ('Esc', 'Esc'), ('F5', 'F5'), ('F6', 'F6'), ('F7', 'F7'), ('F8', 'F8'), ('F9', 'F9'), ('F10', 'F10')], default='Ctrl+S', help_text='Scorciatoia Salva su tutte le maschere di modifica (riparazione, anagrafiche, tabelle, parametri).', max_length=20, verbose_name='Tasto Salva'),
        ),
    ]
