# Generated by Django 6.0.6 on 2026-09-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_ddt_e_sezionale'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazioneprogramma',
            name='ddt_numero_iniziale',
            field=models.PositiveIntegerField(default=1, help_text='Primo numero DDT da assegnare. I successivi partono dal massimo esistente + 1, e non scendono sotto questo valore.', verbose_name='Numerazione DDT iniziale'),
        ),
    ]
