from django.urls import path

from apps.pratiche.views import (
    CategoriaPraticaCreateView,
    CategoriaPraticaDeleteView,
    CategoriaPraticaListView,
    CategoriaPraticaUpdateView,
    ClienteReferenteJsonView,
    ClienteSearchView,
    ComunicazionePraticaCreateView,
    ComunicazionePraticaDeleteView,
    ComunicazionePraticaUpdateView,
    ComunicazioneMailtoRegisterView,
    ComunicazionePraticaFileView,
    ComunicazionePraticaPreviewView,
    FolderPickerView,
    FolderPreviewFileDeleteView,
    FolderPreviewFileOpenView,
    FolderPreviewView,
    MacroCategoriaPraticaCreateView,
    MacroCategoriaPraticaDeleteView,
    MacroCategoriaPraticaListView,
    MacroCategoriaPraticaUpdateView,
    OperatoreCreateView,
    OperatoreDeleteView,
    OperatoreListView,
    OperatoreUpdateView,
    PraticaBustaPrintView,
    PraticaPrivacyPrintView,
    PraticaCreateView,
    PraticaCategoriaAllegatoDeleteView,
    PraticaCategoriaAllegatoDestroyView,
    PraticaCategoriaAllegatoFileView,
    PraticaCategoriaAllegatoOpenView,
    PraticaCategoriaAllegatoPickView,
    PraticaCategoriaAllegatoUploadView,
    PraticaCategoriaCreateView,
    PraticaCategoriaDeleteView,
    PraticaCategoriaFileDeleteView,
    PraticaCategoriaFileDescriptionView,
    PraticaCategoriaFileOpenView,
    PraticaCategoriaFileUnlinkView,
    PraticaCategoriaFileUploadView,
    PraticaCategoriaFileView,
    PraticaCategoriaUpdateView,
    PraticaDeleteView,
    PraticaDetailView,
    PraticaFotoDeleteView,
    PraticaFotoUploadView,
    PraticaListView,
    PraticaMacroCategoriaApplyView,
    PraticaUpdateView,
    StudioTecnicoCreateView,
    StudioTecnicoDeleteView,
    StudioTecnicoListView,
    StudioTecnicoUpdateView,
    TipoOggettoCreateView,
    TipoOggettoDeleteView,
    TipoOggettoListView,
    TipoOggettoUpdateView,
)

app_name = "pratiche"

urlpatterns = [
    path("", PraticaListView.as_view(), name="pratica_list"),
    path("cliente/<int:cliente_pk>/", PraticaListView.as_view(), name="pratica_list_by_cliente"),
    path("clienti/cerca/", ClienteSearchView.as_view(), name="cliente_search"),
    path("cliente/<int:pk>/referente/", ClienteReferenteJsonView.as_view(), name="cliente_referente_json"),
    path("nuova/", PraticaCreateView.as_view(), name="pratica_create"),
    path("cartelle/scegli/", FolderPickerView.as_view(), name="folder_picker"),
    path("cartelle/anteprima/", FolderPreviewView.as_view(), name="folder_preview"),
    path("cartelle/anteprima/file/apri/", FolderPreviewFileOpenView.as_view(), name="folder_preview_file_open"),
    path("cartelle/anteprima/file/elimina/", FolderPreviewFileDeleteView.as_view(), name="folder_preview_file_delete"),
    path("<int:pk>/busta/", PraticaBustaPrintView.as_view(), name="pratica_busta_print"),
    path("<int:pk>/privacy/", PraticaPrivacyPrintView.as_view(), name="pratica_privacy_print"),
    path("<int:pk>/", PraticaDetailView.as_view(), name="pratica_detail"),
    path("<int:pk>/modifica/", PraticaUpdateView.as_view(), name="pratica_update"),
    path("<int:pk>/elimina/", PraticaDeleteView.as_view(), name="pratica_delete"),
    path("<int:pratica_pk>/foto/aggiungi/", PraticaFotoUploadView.as_view(), name="pratica_foto_upload"),
    path("<int:pratica_pk>/foto/<int:pk>/elimina/", PraticaFotoDeleteView.as_view(), name="pratica_foto_delete"),
    path("<int:pratica_pk>/comunicazioni/nuova/", ComunicazionePraticaCreateView.as_view(), name="comunicazione_create"),
    path(
        "<int:pratica_pk>/comunicazioni/registra-mail/",
        ComunicazioneMailtoRegisterView.as_view(),
        name="comunicazione_mailto_register",
    ),
    path(
        "<int:pratica_pk>/comunicazioni/<int:pk>/elimina/",
        ComunicazionePraticaDeleteView.as_view(),
        name="comunicazione_delete",
    ),
    path(
        "<int:pratica_pk>/comunicazioni/<int:pk>/modifica/",
        ComunicazionePraticaUpdateView.as_view(),
        name="comunicazione_update",
    ),
    path("<int:pratica_pk>/comunicazioni/<int:pk>/anteprima/", ComunicazionePraticaPreviewView.as_view(), name="comunicazione_preview"),
    path("<int:pratica_pk>/comunicazioni/<int:pk>/file/", ComunicazionePraticaFileView.as_view(), name="comunicazione_file"),
    path("categorie/", CategoriaPraticaListView.as_view(), name="categoria_pratica_list"),
    path("categorie/nuova/", CategoriaPraticaCreateView.as_view(), name="categoria_pratica_create"),
    path("categorie/<int:pk>/modifica/", CategoriaPraticaUpdateView.as_view(), name="categoria_pratica_update"),
    path("categorie/<int:pk>/elimina/", CategoriaPraticaDeleteView.as_view(), name="categoria_pratica_delete"),
    path("macro-categorie/", MacroCategoriaPraticaListView.as_view(), name="macro_categoria_pratica_list"),
    path("macro-categorie/nuova/", MacroCategoriaPraticaCreateView.as_view(), name="macro_categoria_pratica_create"),
    path("macro-categorie/<int:pk>/modifica/", MacroCategoriaPraticaUpdateView.as_view(), name="macro_categoria_pratica_update"),
    path("macro-categorie/<int:pk>/elimina/", MacroCategoriaPraticaDeleteView.as_view(), name="macro_categoria_pratica_delete"),
    path("studi-tecnici/", StudioTecnicoListView.as_view(), name="studio_tecnico_list"),
    path("studi-tecnici/nuovo/", StudioTecnicoCreateView.as_view(), name="studio_tecnico_create"),
    path("studi-tecnici/<int:pk>/modifica/", StudioTecnicoUpdateView.as_view(), name="studio_tecnico_update"),
    path("studi-tecnici/<int:pk>/elimina/", StudioTecnicoDeleteView.as_view(), name="studio_tecnico_delete"),
    path("operatori/", OperatoreListView.as_view(), name="operatore_list"),
    path("operatori/nuovo/", OperatoreCreateView.as_view(), name="operatore_create"),
    path("operatori/<int:pk>/modifica/", OperatoreUpdateView.as_view(), name="operatore_update"),
    path("operatori/<int:pk>/elimina/", OperatoreDeleteView.as_view(), name="operatore_delete"),
    path("tipi-oggetto/", TipoOggettoListView.as_view(), name="tipo_oggetto_list"),
    path("tipi-oggetto/nuovo/", TipoOggettoCreateView.as_view(), name="tipo_oggetto_create"),
    path("tipi-oggetto/<int:pk>/modifica/", TipoOggettoUpdateView.as_view(), name="tipo_oggetto_update"),
    path("tipi-oggetto/<int:pk>/elimina/", TipoOggettoDeleteView.as_view(), name="tipo_oggetto_delete"),
    path("<int:pratica_pk>/categorie/nuova/", PraticaCategoriaCreateView.as_view(), name="pratica_categoria_create"),
    path("<int:pratica_pk>/macro-categorie/applica/", PraticaMacroCategoriaApplyView.as_view(), name="pratica_macro_categoria_apply"),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/modifica/",
        PraticaCategoriaUpdateView.as_view(),
        name="pratica_categoria_update",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/elimina/",
        PraticaCategoriaDeleteView.as_view(),
        name="pratica_categoria_delete",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/file/",
        PraticaCategoriaFileView.as_view(),
        name="pratica_categoria_file",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/file/apri/",
        PraticaCategoriaFileOpenView.as_view(),
        name="pratica_categoria_file_open",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/file/aggiungi/",
        PraticaCategoriaFileUploadView.as_view(),
        name="pratica_categoria_file_upload",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/file/descrizione/",
        PraticaCategoriaFileDescriptionView.as_view(),
        name="pratica_categoria_file_description",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/file/elimina/",
        PraticaCategoriaFileDeleteView.as_view(),
        name="pratica_categoria_file_delete",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/file/scollega/",
        PraticaCategoriaFileUnlinkView.as_view(),
        name="pratica_categoria_file_unlink",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:categoria_pk>/allegati/aggiungi/",
        PraticaCategoriaAllegatoUploadView.as_view(),
        name="pratica_categoria_allegato_upload",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:categoria_pk>/allegati/scegli/",
        PraticaCategoriaAllegatoPickView.as_view(),
        name="pratica_categoria_allegato_pick",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:categoria_pk>/allegati/<int:pk>/file/",
        PraticaCategoriaAllegatoFileView.as_view(),
        name="pratica_categoria_allegato_file",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:categoria_pk>/allegati/<int:pk>/apri/",
        PraticaCategoriaAllegatoOpenView.as_view(),
        name="pratica_categoria_allegato_open",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:categoria_pk>/allegati/<int:pk>/elimina/",
        PraticaCategoriaAllegatoDeleteView.as_view(),
        name="pratica_categoria_allegato_delete",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:categoria_pk>/allegati/<int:pk>/distruggi/",
        PraticaCategoriaAllegatoDestroyView.as_view(),
        name="pratica_categoria_allegato_destroy",
    ),
]
