# Generated by Django 6.0.6 on 2026-07-08 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0019_alter_comunicazionepratica_allegato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pratica',
            options={'ordering': ['-data_apertura', '-id'], 'verbose_name': 'Pratica', 'verbose_name_plural': 'Riparazioni'},
        ),
        migrations.AddField(
            model_name='pratica',
            name='costo_lavorazione',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo lavorazione (EUR)'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='costo_materiale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo materiale (EUR)'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='data_rientro',
            field=models.DateField(blank=True, null=True, verbose_name='Data rientro'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='data_riparatore',
            field=models.DateField(blank=True, null=True, verbose_name='Data riparatore'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='data_vendita',
            field=models.DateField(blank=True, null=True, verbose_name='Data vendita'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='negozio',
            field=models.CharField(blank=True, max_length=20, verbose_name='Negozio'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='oro_aggiunto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Oro aggiunto (gr)'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='peso_grammi',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Peso (gr)'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='prezzo_al',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prezzo al'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='prezzo_pagato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prezzo pagato'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='riparatore',
            field=models.CharField(blank=True, max_length=150, verbose_name='Riparatore'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='tipo_oggetto',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tipo oggetto'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='responsabile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pratiche_assegnate', to=settings.AUTH_USER_MODEL, verbose_name='Operatore'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='stato',
            field=models.CharField(choices=[('accettazione', 'Accettazione'), ('riparatore', 'Riparatore'), ('in_consegna', 'In consegna'), ('evasa', 'Evasa'), ('non_ritirata', 'Non ritirata'), ('annullata', 'Annullata'), ('archiviata', 'Archiviata'), ('bozza', 'Bozza'), ('aperta', 'Aperta'), ('in_lavorazione', 'In lavorazione'), ('in_attesa_cliente', 'In attesa cliente'), ('in_attesa_esterna', 'In attesa esterna'), ('completata', 'Completata')], default='accettazione', max_length=30, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='tipologia',
            field=models.CharField(choices=[('prezioso', 'Prezioso'), ('non_prezioso', 'Non prezioso')], default='non_prezioso', max_length=30, verbose_name='Tipologia oggetto'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='titolo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Oggetto / titolo scheda'),
        ),
        migrations.AlterField(
            model_name='templatepratica',
            name='tipologia',
            field=models.CharField(choices=[('prezioso', 'Prezioso'), ('non_prezioso', 'Non prezioso')], max_length=30, unique=True, verbose_name='Tipologia'),
        ),
    ]
