# Generated by Django 6.0.6 on 2026-07-08 20:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0020_alter_pratica_options_pratica_costo_lavorazione_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='responsabile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pratiche_assegnate', to=settings.AUTH_USER_MODEL, verbose_name='Responsabile accesso'),
        ),
        migrations.CreateModel(
            name='Operatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('nominativo', models.CharField(max_length=150, unique=True, verbose_name='Nominativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Operatore',
                'verbose_name_plural': 'Operatori',
                'ordering': ['nominativo'],
            },
        ),
        migrations.AddField(
            model_name='pratica',
            name='operatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='riparazioni', to='pratiche.operatore', verbose_name='Operatore'),
        ),
    ]
