# Generated by Django 6.0.6 on 2026-07-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0023_pratica_riparatore_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='negozio',
            field=models.CharField(blank=True, choices=[('PT', 'Pistoia'), ('MO', 'Montale'), ('QU', 'Quarrata')], max_length=2, verbose_name='Negozio'),
        ),
    ]
