# Generated by Django 6.0.6 on 2026-07-09 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0005_anagrafica_tipo'),
        ('pratiche', '0024_pratica_negozio_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratica',
            name='centro_assistenza',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'tipo': 'centro_assistenza'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pratiche_centro_assistenza', to='anagrafiche.anagrafica', verbose_name='Centro assistenza'),
        ),
    ]
