# Generated by Django 6.0.6 on 2026-07-11 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0005_anagrafica_tipo'),
        ('pratiche', '0025_pratica_centro_assistenza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratica',
            name='referente_cellulare',
            field=models.CharField(blank=True, max_length=30, verbose_name='Cellulare'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='referente_cognome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cognome'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='referente_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='referente_nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='referente_telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'tipo': 'cliente'}, on_delete=django.db.models.deletion.PROTECT, related_name='pratiche', to='anagrafiche.anagrafica', verbose_name='Cliente'),
        ),
    ]
