# Generated by Django 6.0.6 on 2026-07-11 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0006_anagrafica_nome_cognome'),
        ('pratiche', '0026_pratica_referente_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'tipo': 'cliente'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pratiche', to='anagrafiche.anagrafica', verbose_name='Cliente'),
        ),
    ]
