# Generated by Django 6.0.6 on 2026-07-19 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0037_pratica_peso_aggiunto_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriapratica',
            options={'ordering': ['denominazione'], 'verbose_name': 'Categoria riparazione', 'verbose_name_plural': 'Categorie riparazioni'},
        ),
        migrations.AlterModelOptions(
            name='comunicazionepratica',
            options={'ordering': ['-data_ora', '-id'], 'verbose_name': 'Comunicazione riparazione', 'verbose_name_plural': 'Comunicazioni riparazione'},
        ),
        migrations.AlterModelOptions(
            name='macrocategoriapratica',
            options={'ordering': ['denominazione'], 'verbose_name': 'Macro-categoria riparazione', 'verbose_name_plural': 'Macro-categorie riparazioni'},
        ),
        migrations.AlterModelOptions(
            name='pratica',
            options={'ordering': ['-data_apertura', '-id'], 'verbose_name': 'Riparazione', 'verbose_name_plural': 'Riparazioni'},
        ),
        migrations.AlterModelOptions(
            name='praticacategoria',
            options={'ordering': ['macro_categoria__denominazione', 'categoria__denominazione', 'versione'], 'verbose_name': 'Categoria riparazione collegata', 'verbose_name_plural': 'Categorie riparazione collegate'},
        ),
        migrations.AlterModelOptions(
            name='praticacategoriaallegato',
            options={'ordering': ['file'], 'verbose_name': 'Allegato singolo categoria riparazione', 'verbose_name_plural': 'Allegati singoli categorie riparazione'},
        ),
        migrations.AlterModelOptions(
            name='praticacategoriafile',
            options={'ordering': ['percorso_relativo'], 'verbose_name': 'File categoria riparazione', 'verbose_name_plural': 'File categorie riparazione'},
        ),
        migrations.AlterModelOptions(
            name='praticamacrocategoria',
            options={'ordering': ['macro_categoria__denominazione'], 'verbose_name': 'Macro-categoria riparazione collegata', 'verbose_name_plural': 'Macro-categorie riparazione collegate'},
        ),
        migrations.AlterModelOptions(
            name='templatepratica',
            options={'ordering': ['tipologia'], 'verbose_name': 'Template riparazione', 'verbose_name_plural': 'Template riparazioni'},
        ),
        migrations.AlterField(
            model_name='comunicazionepratica',
            name='pratica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicazioni', to='pratiche.pratica', verbose_name='Riparazione'),
        ),
        migrations.AlterField(
            model_name='pratica',
            name='data_vendita',
            field=models.DateField(blank=True, null=True, verbose_name='Data vendita/evasione'),
        ),
        migrations.AlterField(
            model_name='praticacategoria',
            name='pratica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_collegamenti', to='pratiche.pratica', verbose_name='Riparazione'),
        ),
        migrations.AlterField(
            model_name='praticacategoriaallegato',
            name='pratica_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati_singoli', to='pratiche.praticacategoria', verbose_name='Categoria riparazione'),
        ),
        migrations.AlterField(
            model_name='praticacategoriafile',
            name='pratica_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_metadati', to='pratiche.praticacategoria', verbose_name='Categoria riparazione'),
        ),
        migrations.AlterField(
            model_name='praticacategoriafile',
            name='scollegato',
            field=models.BooleanField(default=False, verbose_name='Scollegato dalla riparazione'),
        ),
        migrations.AlterField(
            model_name='praticamacrocategoria',
            name='pratica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_categoria_collegamenti', to='pratiche.pratica', verbose_name='Riparazione'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='pratica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnici', to='pratiche.pratica', verbose_name='Riparazione'),
        ),
    ]
