# Generated by Django 6.0.6 on 2026-09-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0042_hide_legacy_securtek_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='gs_barcode',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='EAN assegnato in TB_PREZZICASSE sul gestionale SQL casse.', max_digits=10, null=True, unique=True, verbose_name='Barcode GS'),
        ),
    ]
