# Generated by Django 6.0.6 on 2026-09-15 16:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0013_hide_indirizzo_permissions'),
        ('pratiche', '0043_sync_field_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='senza_spesa',
            field=models.BooleanField(default=False, help_text='Se attivo, consente stato In consegna anche con Prezzo al Pubblico a zero.', verbose_name='Senza spesa'),
        ),
        migrations.CreateModel(
            name='Ddt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('numero', models.PositiveIntegerField(verbose_name='Numero')),
                ('sezionale', models.CharField(default='R', max_length=10, verbose_name='Sezionale')),
                ('data_documento', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data documento')),
                ('destinatario_ragione_sociale', models.CharField(max_length=200, verbose_name='Destinatario')),
                ('destinatario_indirizzo', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo destinatario')),
                ('destinatario_cap', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('destinatario_comune', models.CharField(blank=True, max_length=100, verbose_name='Comune')),
                ('destinatario_provincia', models.CharField(blank=True, max_length=2, verbose_name='Provincia')),
                ('destinatario_partita_iva', models.CharField(blank=True, max_length=20, verbose_name='Partita IVA destinatario')),
                ('destinatario_codice_fiscale', models.CharField(blank=True, max_length=20, verbose_name='Codice fiscale destinatario')),
                ('destinatario_codice_cliente', models.CharField(blank=True, max_length=30, verbose_name='Cod. cliente')),
                ('destinazione_merce', models.TextField(blank=True, verbose_name='Destinazione merce')),
                ('causale', models.CharField(default='C/RIPARAZIONE', max_length=80, verbose_name='Causale')),
                ('aspetto_beni', models.CharField(default='SACCHETTO', max_length=80, verbose_name='Aspetto beni')),
                ('trasporto_a_cura', models.CharField(default='Vettore', max_length=80, verbose_name='Trasporto a cura')),
                ('vettore', models.CharField(default='GLS', max_length=120, verbose_name='Vettore')),
                ('peso_lordo_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peso lordo (kg)')),
                ('colli', models.PositiveIntegerField(default=1, verbose_name='Colli')),
                ('data_inizio_trasporto', models.DateField(blank=True, null=True, verbose_name='Data inizio trasporto')),
                ('ora_inizio_trasporto', models.TimeField(blank=True, null=True, verbose_name='Ora inizio trasporto')),
                ('agente', models.CharField(blank=True, max_length=80, verbose_name='Agente')),
                ('centro_assistenza', models.ForeignKey(limit_choices_to={'is_active': True, 'tipo': 'centro_assistenza'}, on_delete=django.db.models.deletion.PROTECT, related_name='ddt', to='anagrafiche.anagrafica', verbose_name='Centro assistenza')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'DDT',
                'verbose_name_plural': 'DDT',
                'ordering': ['-data_documento', '-numero', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DdtRiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('articolo', models.CharField(blank=True, max_length=60, verbose_name='Articolo')),
                ('descrizione', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('unita_misura', models.CharField(default='NR', max_length=10, verbose_name='UM')),
                ('quantita', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantità')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('ddt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='pratiche.ddt', verbose_name='DDT')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('pratica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ddt_righe', to='pratiche.pratica', verbose_name='Riparazione')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Riga DDT',
                'verbose_name_plural': 'Righe DDT',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ddt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('numero', 'sezionale'), name='pratiche_ddt_numero_sezionale_attivi_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ddtriga',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('ddt', 'pratica'), name='pratiche_ddtriga_ddt_pratica_attivi_uniq'),
        ),
    ]
