# Generated by Django 6.0.6 on 2026-09-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0044_ddt_e_sezionale'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratica',
            name='ddt_data',
            field=models.DateField(blank=True, help_text='Data del documento di trasporto associato alla busta.', null=True, verbose_name='Data DDT'),
        ),
        migrations.AddField(
            model_name='pratica',
            name='ddt_numero',
            field=models.CharField(blank=True, help_text='Numero documento di trasporto (es. 100/R) registrato sulla busta.', max_length=30, verbose_name='N. DDT'),
        ),
    ]
