# Generated by Django 6.0.6 on 2026-07-19 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('pratiche', '0038_parametri_access_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurazionenotificaemail',
            options={'permissions': [('access_parametri_mail_sql', 'Può gestire Parametri mail e SQL')], 'verbose_name': 'Configurazione notifiche email', 'verbose_name_plural': 'Configurazioni notifiche email'},
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='pratica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi_agenda', to='pratiche.pratica', verbose_name='Riparazione'),
        ),
    ]
